exports.directory = require('./services/directory')
exports.gateway = require('./services/gateway')
exports.billing = require('./services/billing')
exports.drive = require('./services/drive')
exports.insight = require('./services/insight')
exports.sendIt = require('./services/sendIt')
exports.connect = require('./services/connect')
exports.system = require('./services/system')
