const crud = require('../helpers/crud')

exports.entitytags = crud('insight', 'entitytags')
exports.jobs = crud('insight', 'jobs')
exports.journals = crud('insight', 'journals')
exports.logs = crud('insight', 'logs')
exports.organizations = crud('insight', 'organizations')
exports.ports = crud('insight', 'ports')
exports.providers = crud('insight', 'providers')
exports.reportareas = crud('insight', 'reportareas')
exports.reportdatas = crud('insight', 'reportdatas')
exports.reportmasters = crud('insight', 'reportmasters')
exports.reports = crud('insight', 'reports')
exports.reporttypes = crud('insight', 'reporttypes')
exports.rfqs = crud('insight', 'rfqs')
exports.tags = crud('insight', 'tags')
exports.tagtypes = crud('insight', 'tagtypes')
exports.targets = crud('insight', 'targets')
exports.targettypes = crud('insight', 'targettypes')
exports.tasks = crud('insight', 'tasks')
exports.templates = crud('insight', 'templates')
exports.tenants = crud('insight', 'tenants')
exports.users = crud('insight', 'users')

