const crud = require('../helpers/crud')

exports.activities = crud('system', 'activities')
exports.applications = crud('system', 'applications')
exports.components = crud('system', 'components')
exports.logs = crud('system', 'logs')
exports.navs = crud('system', 'navs')
exports.organizations = crud('system', 'organizations')
exports.servers = crud('system', 'servers')
exports.setttings = crud('system', 'setttings')
exports.taskTemplates = crud('system', 'task-templates')
exports.tasks = crud('system', 'tasks')
exports.tenants = crud('system', 'tenants')
exports.users = crud('system', 'users')
